12: deploy
14: deploy14

deploy: 
	sudo /usr/bin/packer/packer build dev-ubuntu-deploy.json
base: 
	sudo /usr/bin/packer/packer build dev-ubuntu-base.json

deploy14: 
	sudo /usr/bin/packer/packer build dev-ubuntu14-deploy.json
base14: 
	sudo /usr/bin/packer/packer build dev-ubuntu14-base.json

