all: sync

sync: 
	sudo /usr/bin/packer/packer build chrome-dev-sync.json
fetch: 
	sudo /usr/bin/packer/packer build chrome-dev-fetch.json
base:
	sudo /usr/bin/packer/packer build chrome-dev-base.json

